package com.projeto.th_piscinas_api.service;

import com.projeto.th_piscinas_api.config.NfseProperties;
import com.projeto.th_piscinas_api.model.Invoice;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatusCode;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestClient;

import java.nio.charset.StandardCharsets;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.Base64;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Real integration with Focus NFe — Nationwide NFS-e standard (endpoint
 * {@code /v2/nfsen}), the only one Recife/PE accepts. The old endpoint
 * ({@code /v2/nfse}, ABRASF) returns {@code empresa_nao_habilitada} for
 * municipalities on the nationwide environment.
 *
 * <p>Payload and endpoint validated with an invoice authorized in production
 * (07/26-27/2026, company MRM). Details and error catalog in
 * NFSE-NACIONAL-RECIFE.md (root of the projects repository).</p>
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class FocusNfeClient {

    private static final ZoneOffset RECIFE_OFFSET = ZoneOffset.of("-03:00");
    private static final DateTimeFormatter DATA_COMPETENCIA = DateTimeFormatter.ISO_LOCAL_DATE;

    private final NfseProperties props;

    /** Raw result of a call to Focus. */
    public record FocusResult(int httpStatus, Map<String, Object> body) {
    }

    private String baseUrl() {
        return "producao".equalsIgnoreCase(props.getAmbiente())
                ? "https://api.focusnfe.com.br"
                : "https://homologacao.focusnfe.com.br";
    }

    private String authHeader() {
        String raw = props.getToken() + ":";
        return "Basic " + Base64.getEncoder().encodeToString(raw.getBytes(StandardCharsets.UTF_8));
    }

    private static String digits(String v) {
        return v == null ? "" : v.replaceAll("\\D", "");
    }

    /**
     * Builds the Nationwide NFS-e (DPS) payload from the invoice. Flat (not
     * nested) — exactly the format Focus expects on {@code /v2/nfsen}.
     *
     * @param serieDps  series provided by the issuer (not generated by Focus)
     * @param numeroDps number provided by the issuer, allocated by {@link DpsNumberAllocator}
     */
    public Map<String, Object> buildPayload(Invoice invoice, int serieDps, long numeroDps) {
        OffsetDateTime agora = OffsetDateTime.now(RECIFE_OFFSET);
        LocalDate competencia = invoice.getDataCompetencia() != null
                ? invoice.getDataCompetencia() : agora.toLocalDate();

        Map<String, Object> payload = new LinkedHashMap<>();
        payload.put("data_emissao", agora.format(DateTimeFormatter.ISO_OFFSET_DATE_TIME));
        payload.put("data_competencia", competencia.format(DATA_COMPETENCIA));
        payload.put("serie_dps", serieDps);
        payload.put("numero_dps", numeroDps);
        payload.put("emitente_dps", 1);
        payload.put("codigo_municipio_emissora", Integer.parseInt(digits(props.getCodigoMunicipio())));
        payload.put("cnpj_prestador", digits(props.getCnpjPrestador()));

        // Mandatory in some registrations (error E0116 without it), forbidden in
        // others (error E0120 if sent) — omit when not configured.
        if (props.getInscricaoMunicipal() != null && !props.getInscricaoMunicipal().isBlank()) {
            payload.put("inscricao_municipal_prestador", props.getInscricaoMunicipal());
        }

        payload.put("codigo_opcao_simples_nacional", props.getCodigoOpcaoSimplesNacional());
        payload.put("regime_especial_tributacao", props.getRegimeEspecialTributacao());

        String docTomador = digits(invoice.getClientDocument());
        if (docTomador.length() > 11) {
            payload.put("cnpj_tomador", docTomador);
        } else {
            payload.put("cpf_tomador", docTomador);
        }
        payload.put("razao_social_tomador", invoice.getClientName());

        payload.put("codigo_municipio_prestacao", Integer.parseInt(digits(props.getCodigoMunicipio())));
        payload.put("codigo_tributacao_nacional_iss", Integer.parseInt(props.getCodigoTributacaoNacional()));
        payload.put("codigo_tributacao_municipal_iss", Integer.parseInt(props.getCodigoTributacaoMunicipal()));
        payload.put("descricao_servico",
                invoice.getDescription() == null || invoice.getDescription().isBlank()
                        ? "Prestação de serviço" : invoice.getDescription());
        payload.put("tributacao_iss", props.getTributacaoIss());
        payload.put("tipo_retencao_iss", props.getTipoRetencaoIss());
        payload.put("valor_servico", invoice.getValue());

        // The tax block can't be left empty (schema error: "Element
        // 'trib': Missing child element(s)"). Opted-in and non-opted-in taxpayers use
        // different fields — never both at the same time (error E0713).
        if (props.isOptanteSimplesNacional()) {
            payload.put("percentual_total_tributos_simples_nacional", props.getPercentualTributosSimplesNacional());
        } else {
            payload.put("percentual_total_tributos_federais", props.getPercentualTributosFederais());
            payload.put("percentual_total_tributos_estaduais", props.getPercentualTributosEstaduais());
            payload.put("percentual_total_tributos_municipais", props.getPercentualTributosMunicipais());
        }

        payload.put("finalidade_emissao", 0);
        payload.put("consumidor_final", 0);
        payload.put("indicador_destinatario", 0);
        return payload;
    }

    /** Sends the NFS-e for issuance. {@code ref} is our own reference (idempotency). */
    @SuppressWarnings("unchecked")
    public FocusResult emit(String ref, Map<String, Object> payload) {
        var response = RestClient.create().post()
                .uri(baseUrl() + "/v2/nfsen?ref={ref}", ref)
                .header("Authorization", authHeader())
                .body(payload)
                .retrieve()
                .onStatus(HttpStatusCode::isError, (req, res) -> { /* errors handled via the body */ })
                .toEntity(Map.class);
        return new FocusResult(response.getStatusCode().value(),
                response.getBody() == null ? Map.of() : (Map<String, Object>) response.getBody());
    }

    /** Checks the progress/result of an NFS-e by its {@code ref}. */
    @SuppressWarnings("unchecked")
    public FocusResult consult(String ref) {
        var response = RestClient.create().get()
                .uri(baseUrl() + "/v2/nfsen/{ref}", ref)
                .header("Authorization", authHeader())
                .retrieve()
                .onStatus(HttpStatusCode::isError, (req, res) -> { /* errors handled via the body */ })
                .toEntity(Map.class);
        return new FocusResult(response.getStatusCode().value(),
                response.getBody() == null ? Map.of() : (Map<String, Object>) response.getBody());
    }

    /**
     * Cancels the NFS-e by its {@code ref}. Only works once the invoice is authorized.
     * The cancellation window is limited and varies by municipality — once
     * it passes, the city rejects it and the tax is due.
     */
    @SuppressWarnings("unchecked")
    public FocusResult cancel(String ref, String justificativa) {
        var response = RestClient.create().method(org.springframework.http.HttpMethod.DELETE)
                .uri(baseUrl() + "/v2/nfsen/{ref}", ref)
                .header("Authorization", authHeader())
                .header("Content-Type", "application/json")
                .body(Map.of("justificativa", justificativa))
                .retrieve()
                .onStatus(HttpStatusCode::isError, (req, res) -> { /* errors handled via the body */ })
                .toEntity(Map.class);
        return new FocusResult(response.getStatusCode().value(),
                response.getBody() == null ? Map.of() : (Map<String, Object>) response.getBody());
    }
}
