-- =====================================================================
-- V12 — Controle de manutenção preventiva por cliente (MaintenancePlan)
-- Plano recorrente: frequência em dias + próxima data prevista, usado
-- para apontar clientes em dia, próximos do vencimento ou vencidos.
-- =====================================================================

CREATE TABLE maintenance_plans (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id             BIGINT      NOT NULL,
    description           VARCHAR(255),
    frequency_days        INTEGER     NOT NULL,
    last_maintenance_date DATE,
    next_maintenance_date DATE        NOT NULL,
    active                BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at            TIMESTAMP   NOT NULL DEFAULT now(),
    updated_at            TIMESTAMP,

    CONSTRAINT chk_maintenance_frequency_positive CHECK (frequency_days > 0)
);

-- Cliente é obrigatório. RESTRICT preserva planos de clientes ativos.
ALTER TABLE maintenance_plans
    ADD CONSTRAINT fk_maintenance_plans_client
    FOREIGN KEY (client_id) REFERENCES clients (id)
    ON DELETE RESTRICT;

CREATE INDEX idx_maintenance_plans_next   ON maintenance_plans (next_maintenance_date);
CREATE INDEX idx_maintenance_plans_client ON maintenance_plans (client_id);
CREATE INDEX idx_maintenance_plans_active ON maintenance_plans (active);