-- =====================================================================
-- V16 — Módulo de Fornecedores (Supplier)
-- Cria a tabela suppliers e liga os lançamentos financeiros de saída
-- a um fornecedor (base do gráfico "gasto por fornecedor" do ADM).
-- =====================================================================

CREATE TABLE suppliers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    cnpj        VARCHAR(20),
    email       VARCHAR(255),
    phone       VARCHAR(30),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP,

    CONSTRAINT uk_suppliers_cnpj UNIQUE (cnpj)
);

CREATE INDEX idx_suppliers_name   ON suppliers (name);
CREATE INDEX idx_suppliers_active ON suppliers (active);

-- ---------------------------------------------------------------------
-- Liga o lançamento financeiro ao fornecedor.
-- Coluna anulável: só lançamentos de SAIDA/FORNECEDOR a preenchem.
-- ON DELETE SET NULL: remover um fornecedor não apaga o histórico de gastos.
-- ---------------------------------------------------------------------
ALTER TABLE financial_launch
    ADD COLUMN supplier_id BIGINT;

ALTER TABLE financial_launch
    ADD CONSTRAINT fk_financial_launch_supplier
    FOREIGN KEY (supplier_id) REFERENCES suppliers (id)
    ON DELETE SET NULL;

CREATE INDEX idx_financial_launch_supplier_id ON financial_launch (supplier_id);