-- =====================================================================
-- V16 — Entrada de lote de produtos (compra de mercadoria)
-- Adiciona o preço de custo ao produto e cria as tabelas de entrada de
-- estoque. Registrar uma entrada: soma ao estoque, atualiza o custo do
-- produto e gera uma despesa (SAIDA/FORNECEDOR) no financeiro.
-- =====================================================================

-- Preço de CUSTO do produto (distinto do price, que é o de VENDA).
ALTER TABLE products
    ADD COLUMN IF NOT EXISTS cost_price NUMERIC(12, 2);

-- ---------------------------------------------------------------------
-- stock_entries
-- ---------------------------------------------------------------------
CREATE TABLE stock_entries (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id          BIGINT         NOT NULL,
    document_number      VARCHAR(60),
    total                NUMERIC(12, 2) NOT NULL DEFAULT 0,
    financial_launch_id  BIGINT,
    entry_date           DATE           NOT NULL,
    created_at           TIMESTAMP      NOT NULL DEFAULT now(),

    CONSTRAINT chk_stock_entries_total_nonneg CHECK (total >= 0)
);

ALTER TABLE stock_entries
    ADD CONSTRAINT fk_stock_entries_supplier
    FOREIGN KEY (supplier_id) REFERENCES suppliers (id)
    ON DELETE RESTRICT;

ALTER TABLE stock_entries
    ADD CONSTRAINT fk_stock_entries_financial_launch
    FOREIGN KEY (financial_launch_id) REFERENCES financial_launch (id)
    ON DELETE SET NULL;

CREATE INDEX idx_stock_entries_supplier   ON stock_entries (supplier_id);
CREATE INDEX idx_stock_entries_entry_date ON stock_entries (entry_date);

-- ---------------------------------------------------------------------
-- stock_entry_items
-- ---------------------------------------------------------------------
CREATE TABLE stock_entry_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_entry_id  BIGINT         NOT NULL,
    product_id      BIGINT         NOT NULL,
    quantity        INTEGER        NOT NULL,
    unit_cost       NUMERIC(12, 2) NOT NULL,
    subtotal        NUMERIC(12, 2) NOT NULL,

    CONSTRAINT chk_stock_entry_items_qty_positive CHECK (quantity > 0),
    CONSTRAINT chk_stock_entry_items_cost_nonneg  CHECK (unit_cost >= 0)
);

ALTER TABLE stock_entry_items
    ADD CONSTRAINT fk_stock_entry_items_entry
    FOREIGN KEY (stock_entry_id) REFERENCES stock_entries (id)
    ON DELETE CASCADE;

ALTER TABLE stock_entry_items
    ADD CONSTRAINT fk_stock_entry_items_product
    FOREIGN KEY (product_id) REFERENCES products (id)
    ON DELETE RESTRICT;

CREATE INDEX idx_stock_entry_items_entry   ON stock_entry_items (stock_entry_id);
CREATE INDEX idx_stock_entry_items_product ON stock_entry_items (product_id);