-- =====================================================================
-- V18 — Pedido do vendedor externo (envio para o ADM)
-- O pedido NÃO baixa estoque ao ser enviado; quando o ADM aprova, ele
-- vira uma venda (que aí sim baixa estoque e entra no financeiro).
-- =====================================================================

CREATE TABLE external_orders (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id         BIGINT,
    seller_name       VARCHAR(255),
    customer_name     VARCHAR(255),
    status            VARCHAR(20)    NOT NULL DEFAULT 'ENVIADO',
    total             NUMERIC(12, 2) NOT NULL DEFAULT 0,
    notes             VARCHAR(500),
    rejection_reason  VARCHAR(500),
    processed_by_id   BIGINT,
    processed_at      TIMESTAMP,
    sale_id           BIGINT,
    created_at        TIMESTAMP      NOT NULL DEFAULT now(),

    CONSTRAINT chk_external_orders_total_nonneg CHECK (total >= 0)
);

ALTER TABLE external_orders
    ADD CONSTRAINT fk_external_orders_seller
    FOREIGN KEY (seller_id) REFERENCES usuarios (id) ON DELETE SET NULL;

ALTER TABLE external_orders
    ADD CONSTRAINT fk_external_orders_processed_by
    FOREIGN KEY (processed_by_id) REFERENCES usuarios (id) ON DELETE SET NULL;

ALTER TABLE external_orders
    ADD CONSTRAINT fk_external_orders_sale
    FOREIGN KEY (sale_id) REFERENCES sales (id) ON DELETE SET NULL;

CREATE INDEX idx_external_orders_status ON external_orders (status);
CREATE INDEX idx_external_orders_seller ON external_orders (seller_id);

-- ---------------------------------------------------------------------
CREATE TABLE external_order_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT         NOT NULL,
    product_id  BIGINT         NOT NULL,
    quantity    INTEGER        NOT NULL,
    unit_price  NUMERIC(12, 2) NOT NULL,
    subtotal    NUMERIC(12, 2) NOT NULL,

    CONSTRAINT chk_external_order_items_qty_positive CHECK (quantity > 0)
);

ALTER TABLE external_order_items
    ADD CONSTRAINT fk_external_order_items_order
    FOREIGN KEY (order_id) REFERENCES external_orders (id) ON DELETE CASCADE;

ALTER TABLE external_order_items
    ADD CONSTRAINT fk_external_order_items_product
    FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT;

CREATE INDEX idx_external_order_items_order   ON external_order_items (order_id);
CREATE INDEX idx_external_order_items_product ON external_order_items (product_id);