-- Tabela de usuários (entidade User -> @Table(name = "usuarios"))
CREATE TABLE usuarios (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(255) NOT NULL,
    matricula     VARCHAR(255) NOT NULL,
    senha         VARCHAR(255) NOT NULL,
    perfil        VARCHAR(255) NOT NULL,
    ativo         BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em     TIMESTAMP,
    atualizado_em TIMESTAMP,
    CONSTRAINT uk_usuarios_matricula UNIQUE (matricula)
);
