-- =====================================================================
-- V10 — Módulo de NFS-e (Invoice)
-- Nota de serviço independente: service_order_id é o id da OS (referência,
-- sem FK). Em modo simulação a nota é "SEM VALOR FISCAL".
-- =====================================================================

CREATE TABLE invoices (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference         VARCHAR(120)   NOT NULL,
    service_order_id  VARCHAR(64),
    client_name       VARCHAR(255),
    client_document   VARCHAR(20),
    client_address    VARCHAR(500),
    description       VARCHAR(1000),
    valor             NUMERIC(12, 2) NOT NULL DEFAULT 0,   -- "value" é palavra reservada no H2
    status            VARCHAR(30)    NOT NULL,
    numero_nfse       VARCHAR(60),
    url_pdf           VARCHAR(255),
    url_xml           VARCHAR(255),
    error_message     VARCHAR(1000),
    created_at        TIMESTAMP      NOT NULL DEFAULT now(),

    CONSTRAINT uk_invoices_reference UNIQUE (reference),
    CONSTRAINT chk_invoices_valor_nonneg CHECK (valor >= 0)
);

CREATE INDEX idx_invoices_service_order_id ON invoices (service_order_id);
