-- =====================================================================
-- V22 — Contas a Receber (Receivable)
-- Separa "venda registrada" de "dinheiro recebido": a receita só vira
-- lançamento financeiro quando o ADM confirma o recebimento.
-- =====================================================================

CREATE TABLE receivables (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type          VARCHAR(20)  NOT NULL,           -- VENDA | ORDEM_SERVICO | AVULSO
    source_id            BIGINT,                           -- ex.: id da venda
    client_name          VARCHAR(255),
    description          VARCHAR(255),
    amount               NUMERIC(12, 2) NOT NULL,
    due_date             DATE,
    status               VARCHAR(20)  NOT NULL DEFAULT 'PENDENTE', -- PENDENTE | RECEBIDO | CANCELADO
    payment_method       VARCHAR(20),                      -- DINHEIRO | PIX | CARTAO | BOLETO | TRANSFERENCIA
    received_date        DATE,
    financial_launch_id  BIGINT,
    created_at           TIMESTAMP    NOT NULL DEFAULT now(),

    CONSTRAINT chk_receivables_amount_nonneg CHECK (amount >= 0)
);

-- Lançamento gerado ao confirmar. SET NULL para não travar a remoção do lançamento.
ALTER TABLE receivables
    ADD CONSTRAINT fk_receivables_financial_launch
    FOREIGN KEY (financial_launch_id) REFERENCES financial_launch (id)
    ON DELETE SET NULL;

CREATE INDEX idx_receivables_status   ON receivables (status);
CREATE INDEX idx_receivables_due_date ON receivables (due_date);
CREATE INDEX idx_receivables_source   ON receivables (source_type, source_id);