-- =====================================================================
-- V26 — Registros de serviço (texto + fotos) do técnico
-- As fotos NÃO ficam no banco: guardamos só a URL/referência do arquivo,
-- que mora no storage (disco montado / S3). Evita inchar o Postgres.
-- =====================================================================

CREATE TABLE service_records (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_order_id  BIGINT    NOT NULL,
    author_id         BIGINT,
    note              TEXT,
    created_at        TIMESTAMP NOT NULL DEFAULT now()
);

ALTER TABLE service_records
    ADD CONSTRAINT fk_service_records_order
    FOREIGN KEY (service_order_id) REFERENCES service_orders (id) ON DELETE CASCADE;

ALTER TABLE service_records
    ADD CONSTRAINT fk_service_records_author
    FOREIGN KEY (author_id) REFERENCES usuarios (id) ON DELETE SET NULL;

CREATE INDEX idx_service_records_order ON service_records (service_order_id);

-- ---------------------------------------------------------------------
CREATE TABLE service_record_photos (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_record_id  BIGINT       NOT NULL,
    url                VARCHAR(500) NOT NULL,
    file_name          VARCHAR(255),
    content_type       VARCHAR(100)
);

ALTER TABLE service_record_photos
    ADD CONSTRAINT fk_service_record_photos_record
    FOREIGN KEY (service_record_id) REFERENCES service_records (id) ON DELETE CASCADE;

CREATE INDEX idx_service_record_photos_record ON service_record_photos (service_record_id);