-- =====================================================================
-- V28 — Numeração de DPS (NFS-e Nacional)
-- A Focus NÃO gera numero_dps/serie_dps: quem informa é o emissor, e
-- número repetido é rejeitado pela prefeitura. Uma linha por (cnpj, serie).
-- =====================================================================

CREATE TABLE nfse_dps_sequence (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj           VARCHAR(14)    NOT NULL,
    serie          INTEGER        NOT NULL,
    ultimo_numero  BIGINT         NOT NULL DEFAULT 0,

    CONSTRAINT uk_nfse_dps_sequence_cnpj_serie UNIQUE (cnpj, serie)
);
