-- Lançamentos financeiros (entidade FinancialLaunch -> @Table(name = "financial_launch"))
CREATE TABLE financial_launch (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo      VARCHAR(255)   NOT NULL,
    origem    VARCHAR(255)   NOT NULL,
    valor     NUMERIC(12, 2) NOT NULL,
    data      DATE           NOT NULL,
    descricao VARCHAR(255),
    criado_em TIMESTAMP
);
