ALTER TABLE service_orders
ADD COLUMN IF NOT EXISTS type VARCHAR(20);

UPDATE service_orders
SET type = 'OS'
WHERE type IS NULL;

ALTER TABLE service_orders
ALTER COLUMN type SET NOT NULL;

CREATE TABLE IF NOT EXISTS service_order_items (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_order_id  BIGINT       NOT NULL,
    name              VARCHAR(255) NOT NULL,
    description       TEXT,
    item_value        NUMERIC(12, 2) NOT NULL,

    CONSTRAINT fk_service_order_items_order
        FOREIGN KEY (service_order_id) REFERENCES service_orders (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_service_order_items_order_id ON service_order_items (service_order_id);
