CREATE TABLE service_order_materials (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_order_id  BIGINT         NOT NULL,
    product_id        BIGINT         NOT NULL,
    product_name      VARCHAR(255)   NOT NULL,
    quantity          INTEGER        NOT NULL,
    unit_price        NUMERIC(12, 2) NOT NULL,
    created_by_id     BIGINT,
    created_at        TIMESTAMP      NOT NULL DEFAULT now(),
    CONSTRAINT fk_som_service_order FOREIGN KEY (service_order_id) REFERENCES service_orders (id),
    CONSTRAINT fk_som_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE INDEX idx_som_service_order ON service_order_materials (service_order_id);
