CREATE TABLE products (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255)   NOT NULL,
    description  TEXT,
    code         VARCHAR(255)   NOT NULL,
    manufacturer VARCHAR(255)   NOT NULL,
    price        NUMERIC(10, 2) NOT NULL,
    stock        INTEGER        NOT NULL,
    category     VARCHAR(50)    NOT NULL,
    power_hp     DOUBLE PRECISION,
    max_flow_rate DOUBLE PRECISION,
    voltage      INTEGER,
    active       BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP      NOT NULL,
    updated_at   TIMESTAMP,

    CONSTRAINT uk_products_code UNIQUE (code),
    CONSTRAINT chk_products_price_positive CHECK (price > 0),
    CONSTRAINT chk_products_stock_non_negative CHECK (stock >= 0)
);

CREATE INDEX idx_products_category ON products (category);