CREATE TABLE sales (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name        VARCHAR(255),
    seller_id            BIGINT,
    seller_name          VARCHAR(255),
    total                NUMERIC(12, 2) NOT NULL DEFAULT 0,
    financial_launch_id  BIGINT,
    created_at           TIMESTAMP      NOT NULL DEFAULT now(),

    CONSTRAINT chk_sales_total_nonneg CHECK (total >= 0)
);


ALTER TABLE sales
    ADD CONSTRAINT fk_sales_seller
    FOREIGN KEY (seller_id) REFERENCES usuarios (id)
    ON DELETE SET NULL;

-- FK opcional para o lançamento financeiro gerado pela venda.
-- ON DELETE SET NULL evita travar a exclusão do lançamento.
ALTER TABLE sales
    ADD CONSTRAINT fk_sales_financial_launch
    FOREIGN KEY (financial_launch_id) REFERENCES financial_launch (id)
    ON DELETE SET NULL;

CREATE INDEX idx_sales_created_at ON sales (created_at);
CREATE INDEX idx_sales_seller_id  ON sales (seller_id);


CREATE TABLE sale_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id     BIGINT         NOT NULL,
    product_id  BIGINT         NOT NULL,
    quantity    INTEGER        NOT NULL,
    unit_price  NUMERIC(12, 2) NOT NULL,
    subtotal    NUMERIC(12, 2) NOT NULL,

    CONSTRAINT chk_sale_items_qty_positive CHECK (quantity > 0),
    CONSTRAINT chk_sale_items_unit_price_nonneg CHECK (unit_price >= 0),
    CONSTRAINT chk_sale_items_subtotal_nonneg CHECK (subtotal >= 0)
);


ALTER TABLE sale_items
    ADD CONSTRAINT fk_sale_items_sale
    FOREIGN KEY (sale_id) REFERENCES sales (id)
    ON DELETE CASCADE;

ALTER TABLE sale_items
    ADD CONSTRAINT fk_sale_items_product
    FOREIGN KEY (product_id) REFERENCES products (id)
    ON DELETE RESTRICT;

CREATE INDEX idx_sale_items_sale_id    ON sale_items (sale_id);
CREATE INDEX idx_sale_items_product_id ON sale_items (product_id);