-- =====================================================================
-- V5 — Módulo de Clientes (Client + Address)
-- O Address é @Embeddable: suas colunas moram na própria tabela clients.
-- =====================================================================

CREATE TABLE clients (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    document     VARCHAR(20)  NOT NULL,            -- CPF (PF) ou CNPJ (PJ)
    email        VARCHAR(255),
    phone        VARCHAR(30),
    type         VARCHAR(20)  NOT NULL,            -- PESSOA_FISICA | PESSOA_JURIDICA

    -- Endereço embutido (@Embedded Address)
    street         VARCHAR(255),
    street_number  VARCHAR(20),
    complement     VARCHAR(255),
    district       VARCHAR(120),
    city           VARCHAR(120),
    state          VARCHAR(2),                     -- UF
    zip_code       VARCHAR(10),                    -- CEP

    active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at   TIMESTAMP,

    CONSTRAINT uk_clients_document UNIQUE (document)
);

CREATE INDEX idx_clients_name   ON clients (name);
CREATE INDEX idx_clients_active ON clients (active);