CREATE TABLE service_orders (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id            BIGINT       NOT NULL,
    technician_id        BIGINT,
    title                VARCHAR(255) NOT NULL,
    description          TEXT,
    status               VARCHAR(30)  NOT NULL DEFAULT 'ABERTA',
    scheduled_date       TIMESTAMP,
    price                NUMERIC(12, 2),
    completed_at         TIMESTAMP,
    financial_launch_id  BIGINT,
    created_at           TIMESTAMP    NOT NULL DEFAULT now(),
    updated_at           TIMESTAMP,

    CONSTRAINT chk_service_orders_price_nonneg CHECK (price IS NULL OR price >= 0)
);

ALTER TABLE service_orders
    ADD CONSTRAINT fk_service_orders_client
    FOREIGN KEY (client_id) REFERENCES clients (id)
    ON DELETE RESTRICT;

ALTER TABLE service_orders
    ADD CONSTRAINT fk_service_orders_technician
    FOREIGN KEY (technician_id) REFERENCES usuarios (id)
    ON DELETE SET NULL;

ALTER TABLE service_orders
    ADD CONSTRAINT fk_service_orders_financial_launch
    FOREIGN KEY (financial_launch_id) REFERENCES financial_launch (id)
    ON DELETE SET NULL;

CREATE INDEX idx_service_orders_client_id     ON service_orders (client_id);
CREATE INDEX idx_service_orders_technician_id ON service_orders (technician_id);
CREATE INDEX idx_service_orders_status        ON service_orders (status);
CREATE INDEX idx_service_orders_scheduled     ON service_orders (scheduled_date);