package com.projeto.th_piscinas_api.model;

import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "stock_entries")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class StockEntry {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "supplier_id", nullable = false)
    private Supplier supplier;

    /** Invoice number / purchase document (optional). */
    @Column(name = "document_number")
    private String documentNumber;

    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal total;

    /** Financial entry (expense) generated by this stock entry. */
    @Column(name = "financial_launch_id")
    private Long financialLaunchId;

    @Column(name = "entry_date", nullable = false)
    private LocalDate entryDate;

    @Builder.Default
    @OneToMany(mappedBy = "stockEntry", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<StockEntryItem> items = new ArrayList<>();

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    void onCreate() { this.createdAt = LocalDateTime.now(); }

    public void addItem(StockEntryItem item) {
        item.setStockEntry(this);
        this.items.add(item);
    }

}
